-- VIEW ALL DATA FROM STUDENT --

SELECT * FROM STUDENT;

-- VIEW ALL DATA FROM COLLEGE --

SELECT * FROM COLLEGE;

-- VIEW ALL DATA FROM COURSE --

SELECT * FROM COURSE;

-- INSERT COMMAND --

-- INSERT INTO STUDENT --

INSERT INTO STUDENT (FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,EMAIL,PHONE_NUMBER,ENGINEERING_BRANCH,GENDER,STATE,CITY) VALUES('','','','','','','','','','');

-- INSERT INTO COLLEGE --

INSERT INTO COLLEGE (COLLEGE_NAME) VALUES('');

-- INSERT INTO COURSE --

INSERT INTO COURSE (COURSE_ID,COURSE_NAME,COURSE_BRANCH,COURSE_DESCRIPTION,IMAGE_URL) VALUES('','','','');

-- INSERT INTO COLLEGE STUDENT --

INSERT INTO COLLEGE_STUDENT (STUDENT_ID,COLLEGE_ID) VALUES ((SELECT id FROM STUDENT WHERE USERNAME LIKE ''),(SELECT id FROM COLLEGE WHERE COLLEGE_NAME LIKE ''));

-- INSERT INTO COURSE COLLEGE --

INSERT INTO COURSE_COLLEGE(COURSE_ID,COLLEGE_ID) 
		VALUES ((SELECT id FROM COURSE WHERE COURSE_NAME LIKE ''),
				(SELECT id FROM COLLEGE WHERE COLLEGE_NAME LIKE '')); -- ADD THE VALUE IN VARIABLE --


-- INSERT INTO LIKES/COURSES OF A STUDENT --

INSERT INTO LIKES (USERNAME,COURSE_NAME) 
		VALUES ((SELECT id FROM STUDENT WHERE USERNAME LIKE ''),
				(SELECT id FROM COURSE WHERE COURSE_NAME LIKE '')); -- ADD THE VALUE IN VARIABLE --

-- INSERT INTO CONSULTANCY --

INSERT INTO CONSULTANCY (CONSULTANCY_NAME) VALUES('');

-- SHOW THE STUDENT WITH THE COLLEGE NAME --

SELECT  CONCAT(FIRST_NAME,' ',LAST_NAME) AS STUDENT,COLLEGE_NAME FROM STUDENT INNER JOIN COLLEGE_STUDENT ON STUDENT.id = COLLEGE_STUDENT.STUDENT_ID INNER JOIN COLLEGE ON COLLEGE.id = COLLEGE_STUDENT.COLLEGE_ID;

-- COUNT THE NUMBER OF STUDENTS IN THE SAME COLLEGE --

SELECT COUNT(STUDENT_ID) FROM COLLEGE_STUDENT WHERE COLLEGE_ID LIKE (SELECT ID FROM COLLEGE WHERE COLLEGE_NAME LIKE '') ; 

-- COUNT THE STUDENTS IN ALL COLLEGES --

SELECT COUNT(STUDENT_ID) AS NO_OF_STUDENTS,COLLEGE_NAME FROM COLLEGE_STUDENT 
		INNER JOIN COLLEGE 
		WHERE COLLEGE.ID = COLLEGE_STUDENT.COLLEGE_ID 
		GROUP BY COLLEGE_ID;

-- COURSES OFFERED IN COLLEGE --

SELECT COURSE_NAME,COLLEGE_NAME FROM COURSE INNER JOIN COURSE_COLLEGE ON COURSE.id = COURSE_COLLEGE.COURSE_ID INNER JOIN COLLEGE ON COLLEGE.id = COURSE_COLLEGE.COLLEGE_ID;

-- ALL DETAILS --
SELECT  CONCAT(FIRST_NAME,' ',LAST_NAME) AS STUDENT,ENGINEERING_BRANCH,COLLEGE_NAME,EMAIL,PHONE_NUMBER,GENDER,STATE,CITY FROM STUDENT INNER JOIN COLLEGE_STUDENT ON STUDENT.id = COLLEGE_STUDENT.STUDENT_ID INNER JOIN COLLEGE ON COLLEGE.id = COLLEGE_STUDENT.COLLEGE_ID;


select concat(first_name,' ',last_name)as student,course_name from student inner join likes on student.id = likes.student_id inner join course on course.id = likes.course_id;

-- NUMBER OF LIKES FOR EVERY COURSE ADMIN -- 
SELECT COUNT(STUDENT.ID) AS LIKED,LIKES.COURSE_ID FROM LIKES INNER JOIN COURSE ON COURSE.id = LIKES.COURSE_ID INNER JOIN STUDENT ON STUDENT.ID = LIKES.STUDENT_ID GROUP BY LIKES.COURSE_ID;
